function AppleMusicPlayActivity = importfile_apple_music_2021(filename, dataLines)
%IMPORTFILE Import data from a text file
%  APPLEMUSICPLAYACTIVITY = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  APPLEMUSICPLAYACTIVITY = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  AppleMusicPlayActivity = importfile("/Users/kberman6/code/personal/Kevin Apple Music Analysis/Apple Music Activity 2021/Apple Music Play Activity.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-Dec-2021 10:19:18

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 38);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["AppleIDNumber", "AppleMusicSubscription", "ArtistName", "BuildVersion", "ClientIPAddress", "DeviceIdentifier", "EndPositionInMilliseconds", "EndReasonType", "EventEndTimestamp", "EventReasonHintType", "EventReceivedTimestamp", "EventStartTimestamp", "EventType", "FeatureName", "ItemType", "MediaDurationInMilliseconds", "MediaType", "MetricsBucketId", "MetricsClientId", "MillisecondsSincePlay", "Offline", "PlayDurationMilliseconds", "ProvidedAudioBitDepth", "ProvidedAudioChannel", "ProvidedAudioSampleRate", "ProvidedBitRate", "ProvidedCodec", "ProvidedPlaybackFormat", "SessionIsShared", "SharedActivityDevicesCurrent", "SharedActivityDevicesMax", "SongName", "SourceType", "StartPositionInMilliseconds", "StoreFrontName", "UsersAudioQuality", "UsersPlaybackFormat", "UTCOffsetInSeconds"];
opts.VariableTypes = ["double", "categorical", "string", "categorical", "string", "categorical", "double", "categorical", "string", "categorical", "string", "string", "categorical", "categorical", "categorical", "double", "categorical", "double", "categorical", "double", "categorical", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "categorical", "double", "categorical", "string", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["ArtistName", "ClientIPAddress", "EventEndTimestamp", "EventReceivedTimestamp", "EventStartTimestamp", "ProvidedAudioBitDepth", "ProvidedAudioChannel", "ProvidedAudioSampleRate", "ProvidedBitRate", "ProvidedCodec", "ProvidedPlaybackFormat", "SessionIsShared", "SharedActivityDevicesCurrent", "SharedActivityDevicesMax", "SongName", "UsersAudioQuality", "UsersPlaybackFormat"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["AppleMusicSubscription", "ArtistName", "BuildVersion", "ClientIPAddress", "DeviceIdentifier", "EndReasonType", "EventEndTimestamp", "EventReasonHintType", "EventReceivedTimestamp", "EventStartTimestamp", "EventType", "FeatureName", "ItemType", "MediaType", "MetricsClientId", "Offline", "ProvidedAudioBitDepth", "ProvidedAudioChannel", "ProvidedAudioSampleRate", "ProvidedBitRate", "ProvidedCodec", "ProvidedPlaybackFormat", "SessionIsShared", "SharedActivityDevicesCurrent", "SharedActivityDevicesMax", "SongName", "SourceType", "StoreFrontName", "UsersAudioQuality", "UsersPlaybackFormat"], "EmptyFieldRule", "auto");

% Import the data
AppleMusicPlayActivity = readtable(filename, opts);

end